#!/usr/bin/env Rscript
# =============================================================================
# run_engagement.R
# One-command orchestrator: executes the full delivery flow for a single
# engagement config -- data generation (optional) -> intake (optional) ->
# validation report -> PACTA -> TRISK prepare -> TRISK per sector -> scenario
# grid (optional) -> prioritization -> snapshot -> scoring -> letters
# (optional) -> disclosure (optional) -> refresh audit (optional) -- writing
# a pipeline_manifest.json.
#
# Wave 1 PHASE-05 (orchestrator convergence): this is now the SINGLE
# orchestrator for both the public MCB demo and every client engagement.
# scripts/pipeline_refresh.R is a thin wrapper that delegates here with
# engagements/mcb-demo/engagement_config.json.
#
# Usage:
#   Rscript scripts/run_engagement.R --config engagements/<slug>/engagement_config.json [--full] [--raw-loanbook <path>] [--skip-intake] [--top-n <int>] [--dry-run]
#
# --full: sets run_data_generation TRUE for this run (regenerates the
#   synthetic input data first). Only meaningful for mcb-demo in practice --
#   other engagements' data isn't generated by scripts/generate_vietnam_data.R.
# --raw-loanbook <path>: runs intake_validate_and_map.R against <path> first,
#   then all later steps use a resolved config whose inputs$loanbook_csv
#   points at the normalized output. Omit to fall back to the config's
#   inputs$raw_loanbook_csv (if set), or to run the pipeline against the
#   loanbook already named in the engagement config.
# --skip-intake: even with a raw loanbook resolved (flag or config), skip the
#   intake + validation report steps (useful for re-running downstream
#   stages only).
# --top-n <int>: forwarded to generate_engagement_letters.R as --top_n.
# --dry-run: print the resolved step list (one "name: script args" line per
#   step) and exit 0 without executing or writing anything.
#
# Guard rail: refuses to run when the config's snapshot_dir is the public
# dashboard/data unless the config sets public_snapshot_allowed: true
# (prevents an engagement from overwriting the public snapshot).
# =============================================================================

suppressPackageStartupMessages({
  library(jsonlite)
})

source("R/engagement_config.R")
source("R/step_runner.R")

args <- commandArgs(trailingOnly = TRUE)

get_flag_value <- function(args, name) {
  idx <- which(args == name)
  if (length(idx) == 0 || idx[[1]] >= length(args)) return(NULL)
  args[[idx[[1]] + 1]]
}

config_path <- get_flag_value(args, "--config")
if (is.null(config_path)) {
  stop(paste(
    "Usage: Rscript scripts/run_engagement.R --config <path>",
    "[--full] [--raw-loanbook <path>] [--skip-intake] [--top-n <int>] [--dry-run]"
  ), call. = FALSE)
}

skip_intake  <- "--skip-intake" %in% args
top_n        <- get_flag_value(args, "--top-n")
dry_run      <- "--dry-run" %in% args
full_flag    <- "--full" %in% args

cfg <- load_engagement_config(config_path)
if (full_flag) {
  cfg$run_data_generation <- TRUE
}

# A CLI --raw-loanbook flag wins; otherwise fall back to the config's own
# inputs$raw_loanbook_csv so an engagement config can reproduce its own run
# without an out-of-band flag (Wave 1 PHASE-02, C3). %||% is base R (>= 4.4.0).
raw_loanbook <- get_flag_value(args, "--raw-loanbook") %||% cfg$inputs$raw_loanbook_csv

# --- Guard rail: never let an engagement publish into the public snapshot
# directory unless its config explicitly allows it. -------------------------
if (identical(cfg$paths$snapshot_dir, "dashboard/data") && !isTRUE(cfg$public_snapshot_allowed)) {
  stop("Engagement snapshot_dir must not be the public dashboard/data unless public_snapshot_allowed is true", call. = FALSE)
}

run_intake <- !is.null(raw_loanbook) && !skip_intake
intake_dir <- file.path("engagements", cfg$bank_slug, "intake")
effective_config_path <- if (run_intake) {
  file.path("engagements", cfg$bank_slug, "engagement_config.resolved.json")
} else {
  config_path
}

# --- Build the ordered step list --------------------------------------------

build_step_list <- function(cfg, effective_config_path, run_intake, raw_loanbook, intake_dir, top_n) {
  steps <- list()

  if (isTRUE(cfg$run_data_generation)) {
    # scripts/generate_vietnam_data.R is config-unaware (always writes the
    # MCB defaults); it is only meaningful for mcb-demo.
    steps <- c(steps, list(list(
      name = "generate_vietnam_data", script = "scripts/generate_vietnam_data.R", args = character()
    )))
  }

  if (run_intake) {
    intake_args <- c("--input", raw_loanbook, "--output-dir", intake_dir)
    if (isTRUE(cfg$anonymize)) intake_args <- c(intake_args, "--anonymize")
    # Wave 2 PHASE-05 (ASM-006): forward the configured FX rate so USD rows
    # are converted once at intake instead of being retained as NA. Empty
    # shapes (NULL / list() / character(0)) round-trip as "not configured".
    if (length(cfg$inputs$fx_rate_usd_vnd) > 0) {
      intake_args <- c(intake_args, "--fx-rate-usd-vnd", as.character(cfg$inputs$fx_rate_usd_vnd))
    }
    steps <- c(steps, list(list(
      name = "intake", script = "scripts/intake_validate_and_map.R", args = intake_args
    )))
    steps <- c(steps, list(list(
      name = "validation_report",
      script = "scripts/generate_validation_report.R",
      args = c(
        "--intake-dir", intake_dir,
        "--output", file.path(cfg$paths$reports_dir, "Intake_Validation_Report.html"),
        "--bank-name", cfg$bank_name
      )
    )))
    # Wave 2 PHASE-06 (coverage & reconciliation): money-denominated report of
    # submitted vs processed vs dropped exposure and ABCD asset-level coverage.
    # Sits inside the same if (run_intake) branch -- engagements with no raw
    # loanbook (mcb-demo) never run intake and so never run this step.
    steps <- c(steps, list(list(
      name = "coverage_report",
      script = "scripts/generate_coverage_report.R",
      args = c(
        "--config", effective_config_path,
        "--intake-dir", intake_dir,
        "--output", file.path(cfg$paths$reports_dir, "Coverage_Reconciliation_Report.html")
      )
    )))
  }

  steps <- c(steps, list(
    list(name = "pacta_vietnam_scenario", script = "scripts/pacta_vietnam_scenario.R", args = c("--config", effective_config_path)),
    list(name = "trisk_prepare_inputs", script = "scripts/trisk_prepare_inputs.R", args = c("--config", effective_config_path))
  ))

  # Power first, for continuity with the default pipeline's step naming.
  sectors <- cfg$trisk_sectors
  if ("power" %in% sectors) sectors <- c("power", setdiff(sectors, "power"))
  for (sector in sectors) {
    steps <- c(steps, list(list(
      name = sprintf("trisk_sector_demo_%s", sector),
      script = "scripts/trisk_sector_demo.R",
      args = c(sector, "--config", effective_config_path)
    )))
  }

  if (isTRUE(cfg$run_grid)) {
    steps <- c(steps, list(list(
      name = "trisk_scenario_grid", script = "scripts/trisk_scenario_grid.R", args = c("--config", effective_config_path)
    )))
  }

  steps <- c(steps, list(
    list(name = "sector_prioritization", script = "scripts/sector_prioritization.R", args = c("--config", effective_config_path)),
    list(name = "refresh_dashboard_data", script = "scripts/refresh_dashboard_data.R", args = c("--config", effective_config_path)),
    list(name = "engagement_scoring", script = "scripts/engagement_scoring.R", args = c("--config", effective_config_path))
  ))

  if (isTRUE(cfg$run_outputs)) {
    letters_args <- c("--config", effective_config_path)
    if (!is.null(top_n)) letters_args <- c(letters_args, "--top_n", top_n)
    steps <- c(steps, list(list(
      name = "generate_engagement_letters", script = "scripts/generate_engagement_letters.R", args = letters_args
    )))

    steps <- c(steps, list(list(
      name = "generate_disclosure_pack", script = "scripts/generate_disclosure_pack.R", args = c("--config", effective_config_path)
    )))
  }

  if (isTRUE(cfg$run_refresh_audit)) {
    # scripts/generate_refresh_audit.R is config-unaware (always reads the
    # MCB default paths); it is only meaningful for mcb-demo.
    steps <- c(steps, list(list(
      name = "refresh_audit", script = "scripts/generate_refresh_audit.R", args = character()
    )))
  }

  steps
}

full_steps <- build_step_list(cfg, effective_config_path, run_intake, raw_loanbook, intake_dir, top_n)

# --- Banner ------------------------------------------------------------------

cat(sprintf(
  "Engagement: %s (%s)\nEffective config: %s\nLoanbook: %s\n\n",
  cfg$bank_name, cfg$bank_slug, effective_config_path,
  if (!is.null(raw_loanbook)) raw_loanbook else cfg$inputs$loanbook_csv
))

if (dry_run) {
  cat("--dry-run: resolved step list (nothing executed)\n\n")
  for (s in full_steps) {
    cat(sprintf("%s: %s %s\n", s$name, s$script, paste(s$args, collapse = " ")))
  }
  quit(status = 0)
}

# --- Execute -------------------------------------------------------------

if (run_intake) {
  # Locate "intake" by name, not by position: run_data_generation may have
  # prepended a generate_vietnam_data step ahead of it (Wave 1 PHASE-05).
  intake_idx <- which(vapply(full_steps, function(s) identical(s$name, "intake"), logical(1)))[[1]]
  steps_before_intake <- if (intake_idx > 1) full_steps[seq_len(intake_idx - 1)] else list()
  intake_step <- full_steps[[intake_idx]]
  steps_after_intake <- full_steps[-seq_len(intake_idx)]

  pre_results <- if (length(steps_before_intake) > 0) run_steps(steps_before_intake) else list()
  pre_ok <- all(vapply(pre_results, function(s) s$status == "ok", logical(1)))

  if (!pre_ok) {
    step_results <- pre_results
  } else {
    intake_result <- run_step(intake_step)
    if (intake_result$status != "ok") {
      step_results <- c(pre_results, list(intake_result))
    } else {
      dir.create(dirname(effective_config_path), recursive = TRUE, showWarnings = FALSE)
      resolved_cfg <- cfg
      resolved_cfg$inputs$loanbook_csv <- file.path(intake_dir, "normalized_loanbook.csv")
      write(toJSON(resolved_cfg, auto_unbox = TRUE, pretty = TRUE), effective_config_path)
      step_results <- c(pre_results, list(intake_result), run_steps(steps_after_intake))
    }
  }
} else {
  step_results <- run_steps(full_steps)
}

# Public engagements (mcb-demo) write the manifest alongside the public
# snapshot, matching where scripts/pipeline_refresh.R always wrote it, so
# its delegation to this script is observationally identical. Every other
# engagement keeps its manifest under its own engagements/<slug>/ tree.
manifest_path <- if (isTRUE(cfg$public_snapshot_allowed)) {
  file.path(cfg$paths$snapshot_dir, "pipeline_manifest.json")
} else {
  file.path("engagements", cfg$bank_slug, "pipeline_manifest.json")
}
write_pipeline_manifest(
  step_results, manifest_path,
  row_count_files = cfg$row_count_files,
  extra = list(bank_slug = cfg$bank_slug, config_path = effective_config_path)
)
cat(sprintf("\n[OK] Manifest written: %s\n", manifest_path))

manifest_status <- if (all(vapply(step_results, function(s) s$status == "ok", logical(1)))) "ok" else "failed"
if (!identical(manifest_status, "ok")) {
  quit(status = 1)
}

cat("\nEngagement run complete.\n")
