#!/usr/bin/env Rscript
# =============================================================================
# run_engagement.R
# One-command orchestrator: executes the full delivery flow for a single
# engagement config -- data generation (optional) -> intake (optional) ->
# validation report -> PACTA -> TRISK prepare -> TRISK per sector -> scenario
# grid (optional) -> prioritization -> snapshot -> scoring -> letters
# (optional) -> disclosure (optional) -> refresh audit (optional) -- writing
# a pipeline_manifest.json.
#
# Wave 1 PHASE-05 (orchestrator convergence): this is now the SINGLE
# orchestrator for both the public MCB demo and every client engagement.
# scripts/pipeline_refresh.R is a thin wrapper that delegates here with
# engagements/mcb-demo/engagement_config.json.
#
# Usage:
#   Rscript scripts/run_engagement.R --config engagements/<slug>/engagement_config.json [--full] [--raw-loanbook <path>] [--skip-intake] [--top-n <int>] [--only-step <name> [--only-step <name> ...]] [--resume-from <name>] [--allow-partial-manifest] [--dry-run]
#
# --full: sets run_data_generation TRUE for this run (regenerates the
#   synthetic input data first). Only meaningful for mcb-demo in practice --
#   other engagements' data isn't generated by scripts/generate_vietnam_data.R.
# --raw-loanbook <path>: runs intake_validate_and_map.R against <path> first,
#   then all later steps use a resolved config whose inputs$loanbook_csv
#   points at the normalized output. Omit to fall back to the config's
#   inputs$raw_loanbook_csv (if set), or to run the pipeline against the
#   loanbook already named in the engagement config.
# --skip-intake: even with a raw loanbook resolved (flag or config), skip the
#   intake + validation report steps (useful for re-running downstream
#   stages only).
# --top-n <int>: forwarded to generate_engagement_letters.R as --top_n.
# --only-step <name>: run only the named step(s) from the resolved list.
#   Repeatable. An unknown name is a hard error naming the valid step names
#   for this run. Combine with --dry-run to preview the filtered list.
# --resume-from <name>: drop every step before the first whose name matches,
#   then run the rest. Combine with --only-step (applied first, then
#   --resume-from filters the result).
# --allow-partial-manifest: permit a filtered run (--only-step/--resume-from)
#   to overwrite an existing COMPLETE manifest in the public snapshot. The
#   written manifest is marked "partial": true either way; without this flag
#   the orchestrator refuses rather than destroying the full-run record.
# --dry-run: print the resolved step list (one "name: script args" line per
#   step) and exit 0 without executing or writing anything.
#
# Guard rail: refuses to run when the config's snapshot_dir is the public
# dashboard/data unless the config sets public_snapshot_allowed: true
# (prevents an engagement from overwriting the public snapshot).
# =============================================================================

suppressPackageStartupMessages({
  library(jsonlite)
})

source("R/engagement_config.R")
source("R/step_runner.R")
source("R/step_registry.R")
source("R/engagement_plan.R")

args <- commandArgs(trailingOnly = TRUE)
cli <- parse_engagement_cli(args)

config_path <- cli$config_path
dry_run <- cli$dry_run
only_steps <- cli$only_steps
resume_from <- cli$resume_from
# Wave 4 PHASE-02: opt-in to overwriting a complete public manifest with a
# partial (filtered) run's manifest.
allow_partial_manifest <- cli$allow_partial_manifest

cfg <- load_engagement_config(config_path)

# --- Build the ordered step list --------------------------------------------
# Wave 5 (orchestrator deepening): planning lives behind the seam in
# R/engagement_plan.R::plan_engagement_run(). The script keeps the returned
# locals it still executes inline; the intake split and manifest policy
# follow in later steps.

plan <- plan_engagement_run(cfg, cli)
cfg <- plan$cfg
raw_loanbook <- plan$raw_loanbook
run_intake <- plan$run_intake
intake_dir <- plan$intake_dir
effective_config_path <- plan$effective_config_path
full_steps <- plan$steps

# --- Guard rail: never let an engagement publish into the public snapshot
# directory unless its config explicitly allows it. (Moves behind the
# planning seam in a later step; kept inline here so this step stays small.)
if (identical(cfg$paths$snapshot_dir, "dashboard/data") && !isTRUE(cfg$public_snapshot_allowed)) {
  stop("Engagement snapshot_dir must not be the public dashboard/data unless public_snapshot_allowed is true", call. = FALSE)
}

# --- Banner ------------------------------------------------------------------

cat(sprintf(
  "Engagement: %s (%s)\nEffective config: %s\nLoanbook: %s\n\n",
  cfg$bank_name, cfg$bank_slug, effective_config_path,
  if (!is.null(raw_loanbook)) raw_loanbook else cfg$inputs$loanbook_csv
))

if (dry_run) {
  cat("--dry-run: resolved step list (nothing executed)\n\n")
  for (s in full_steps) {
    cat(sprintf("%s: %s %s\n", s$name, s$script, paste(s$args, collapse = " ")))
  }
  quit(status = 0)
}

# --- Execute -------------------------------------------------------------
# The intake split comes from the plan (by name, not by position).
# --only-step / --resume-from can filter "intake" out even when run_intake
# is TRUE; then intake_present is FALSE and we fall through to the plain
# run_steps() branch, the same way --skip-intake already does.

if (run_intake && plan$intake_present) {
  steps_before_intake <- plan$steps_before_intake
  intake_step <- plan$intake_step
  steps_after_intake <- plan$steps_after_intake

  pre_results <- if (length(steps_before_intake) > 0) run_steps(steps_before_intake) else list()
  pre_ok <- all(vapply(pre_results, function(s) s$status == "ok", logical(1)))

  if (!pre_ok) {
    step_results <- pre_results
  } else {
    intake_result <- run_step(intake_step)
    if (intake_result$status != "ok") {
      step_results <- c(pre_results, list(intake_result))
    } else {
      dir.create(dirname(effective_config_path), recursive = TRUE, showWarnings = FALSE)
      resolved_cfg <- cfg
      resolved_cfg$inputs$loanbook_csv <- file.path(intake_dir, "normalized_loanbook.csv")
      write(toJSON(resolved_cfg, auto_unbox = TRUE, pretty = TRUE), effective_config_path)
      step_results <- c(pre_results, list(intake_result), run_steps(steps_after_intake))
    }
  }
} else {
  step_results <- run_steps(full_steps)
}

# Public engagements (mcb-demo) write the manifest alongside the public
# snapshot, matching where scripts/pipeline_refresh.R always wrote it, so
# its delegation to this script is observationally identical. Every other
# engagement keeps its manifest under its own engagements/<slug>/ tree.
manifest_path <- if (isTRUE(cfg$public_snapshot_allowed)) {
  file.path(cfg$paths$snapshot_dir, "pipeline_manifest.json")
} else {
  file.path("engagements", cfg$bank_slug, "pipeline_manifest.json")
}
# Wave 4 PHASE-02: a --only-step / --resume-from run produces a manifest that
# describes only the steps it ran. Writing that over a complete manifest
# silently destroys the provenance record -- and the refresh audit, which reads
# this file, then renders the remains as though they were a full run. Mark it,
# and refuse to clobber a complete PUBLIC manifest without an explicit opt-in.
run_is_partial <- length(only_steps) > 0 || (!is.na(resume_from) && nzchar(resume_from))

if (run_is_partial && isTRUE(cfg$public_snapshot_allowed) &&
    !allow_partial_manifest && file.exists(manifest_path)) {
  existing <- tryCatch(
    jsonlite::fromJSON(manifest_path, simplifyVector = TRUE),
    error = function(e) NULL
  )
  existing_is_complete <- !is.null(existing) && !isTRUE(existing$partial)
  if (existing_is_complete) {
    stop(sprintf(paste0(
      "Refusing to overwrite the complete public manifest at %s with a partial run.\n",
      "  This run was filtered by %s.\n",
      "  Re-run without --only-step/--resume-from, or pass --allow-partial-manifest ",
      "to accept a partial provenance record."
    ), manifest_path, paste(c(
      if (length(only_steps) > 0) sprintf("--only-step %s", paste(only_steps, collapse = ", ")),
      if (!is.na(resume_from) && nzchar(resume_from)) sprintf("--resume-from %s", resume_from)
    ), collapse = " and ")), call. = FALSE)
  }
}

write_pipeline_manifest(
  step_results, manifest_path,
  row_count_files = cfg$row_count_files,
  extra = list(
    bank_slug = cfg$bank_slug, config_path = effective_config_path,
    scenario_vintage = cfg$inputs$scenario_vintage
  ),
  partial = run_is_partial,
  filters = list(only_step = only_steps, resume_from = resume_from)
)
cat(sprintf("\n[OK] Manifest written: %s\n", manifest_path))

manifest_status <- if (all(vapply(step_results, function(s) s$status == "ok", logical(1)))) "ok" else "failed"
if (!identical(manifest_status, "ok")) {
  quit(status = 1)
}

cat("\nEngagement run complete.\n")
